// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYGxnelQSYju6AqvWR3H25rYtzvdLR2kQ',
    appId: '1:911288370249:ios:cdcc0fc097337df2326b98',
    messagingSenderId: '911288370249',
    projectId: 'sfera3-5507a',
    storageBucket: 'sfera3-5507a.appspot.com',
    iosClientId: '911288370249-5aa88eermbsri0q8p8e10fbgk9lfkppp.apps.googleusercontent.com',
    iosBundleId: 'com.example.sferaApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgjdylgEWur-8DQSxJ2zUOPQlOBGb5lTE',
    appId: '1:911288370249:web:3b2aaee5d685c533326b98',
    messagingSenderId: '911288370249',
    projectId: 'sfera3-5507a',
    authDomain: 'sfera3-5507a.firebaseapp.com',
    storageBucket: 'sfera3-5507a.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCgjdylgEWur-8DQSxJ2zUOPQlOBGb5lTE',
    appId: '1:911288370249:web:4e8759b44ed97a2e326b98',
    messagingSenderId: '911288370249',
    projectId: 'sfera3-5507a',
    authDomain: 'sfera3-5507a.firebaseapp.com',
    storageBucket: 'sfera3-5507a.appspot.com',
  );
}
